# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cette fonction permet de calculer les duration pour un portfeuille obligataire.
#'
#' @name calcul_duration_obligation
#' @docType methods
#' @param coupon un vecteur contenant \code{numeric} les coupons.
#' @param mat_res un vecteur \code{numeric} contenant les maturites residuelles.
#' @param valeur_remboursement un vecteur \code{numeric} contenant les valeurs de remboursement.
#' @param yield un vecteur contenant la courbe de taux utilisee.
#' @author Damien Tichit pour Sia Partners
#' @export
#' @include
NULL

calcul_duration_obligation <- function(coupon, mat_res, valeur_remboursement, yield) {
    .Call('_SiALM_calcul_duration_obligation', PACKAGE = 'SiALM', coupon, mat_res, valeur_remboursement, yield)
}

#' Cette fonction permet de calculer les valeurs de marche pour un portfeuille obligataire.
#'
#' @name calcul_vm_obligation
#' @docType methods
#' @param coupon un vecteur contenant \code{numeric} les coupons.
#' @param mat_res un vecteur \code{numeric} contenant les maturites residuelles.
#' @param valeur_remboursement un vecteur \code{numeric} contenant les valeurs de remboursement.
#' @param spread un vecteur \code{numeric} contenant les spread.
#' @param yield un vecteur contenant la courbe de taux utilisee.
#' @author Damien Tichit pour Sia Partners
#' @export
#' @include
NULL

calcul_vm_obligation <- function(coupon, mat_res, valeur_remboursement, spread, yield) {
    .Call('_SiALM_calcul_vm_obligation', PACKAGE = 'SiALM', coupon, mat_res, valeur_remboursement, spread, yield)
}

